- name: Install dependencies
        run: flutter pub get

      - name: Run Analyze
        run: flutter analyze
        continue-on-error: true # يمنع توقف الأتمتة إذا وُجدت تحذيرات في الكود

      - name: Run Automation Tests
        run: flutter test
        continue-on-error: true # يمنع الفشل إذا لم تكن قد كتبت اختبارات محددة بعد
